linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic

linters-settings:
  govet:
    enable-all: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/marcgeld/ruuvi

issues:
  exclude-dirs:
    - examples
  max-same-issues: 0
  max-issues-per-linter: 0

run:
  timeout: 5m
  tests: true
